package com.shabdamsdk.event;

public class CleverTapEventConstants {
    public static final String DEFAULT_VALUE_NA = "NA";
    public static final String DISCOVER_SPOTLIGHT = "discover_spotlight";
    public static final String DEVICE_TYPE = "device_type";
    public static final String ANDROID = "android";
    public static final String APP_INSTALLED = "App_intalled";
    public static final String APP_LAUNCHED = "App_launched";
    public static final String FIRST_OPEN = "First_open";
    public static final String SIGN_UP = "sign_up";
    public static final String PLAY_GUEST = "play_guest";
    public static final String NEXT_1 = "next_1";
    public static final String NEXT_2 = "next_2";
    public static final String NEXT_3 = "next_3";
    public static final String NEXT_4 = "next_4";
    public static final String SKIP_1 = "skip_1";
    public static final String SKIP_2 = "skip_2";
    public static final String SKIP_3 = "skip_3";
    public static final String SKIP_4 = "skip_4";
    public static final String START_GAME = "start_game";
    public static final String GO_FORWARD = "go_forward";
    public static final String DONOTSHOW = "donotshow";
    public static final String QUESTION_MARK = "question_mark";
    public static final String LEADERBOARD_ICON = "leaderboard_icon";
    public static final String STATISTICS_ICON = "statistics_icon";
    public static final String GAME_PLAY = "game_play";
    public static final String HINT_BUTTON = "hint_button";
    public static final String UTTAR_DEKHO = "uttar_dekho";
    public static final String BACK_SPACE = "back_space";
    public static final String ENTER = "enter";
    public static final String NOTIFICATION_ON = "notification_on";
    public static final String NOTIFICATION_OFF = "notification_off";
    public static final String FEEDBACK = "feedback";
    public static final String FAQ = "faq";
    public static final String SUBMIT_WORD = "submit_word";
    public static final String LOGOUT_ICON = "logout_icon";
    public static final String SP_GOOGLE_LOGIN = "sp_google_login";
    public static final String SP_SHARE = "sp_share";
    public static final String SP_AGLA_SHABD = "sp_agla_shabd";
    public static final String LB_SHARE = "lb_share";
    public static final String LB_AGLA_SHABD = "lb_agla_shabd";
    public static final String LB_GOOGLE_LOGIN = "lb_google_login";
}
